//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enable_Now_Konnektor.locals {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal de_DE() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Enable_Now_Konnektor.locals.de-DE", typeof(de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Ergebnis des Converter-Service konnte nicht ausgewertet werden. Möglicherweise wurde eine ungültige Antwort erhalten. ähnelt.
        /// </summary>
        internal static string ConverterServiceMessage01 {
            get {
                return ResourceManager.GetString("ConverterServiceMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Element {0} soll nicht indexiert werden. ähnelt.
        /// </summary>
        internal static string CrawlerIndexerInterfaceMessage01 {
            get {
                return ResourceManager.GetString("CrawlerIndexerInterfaceMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lösche das Element {0} aus dem Index. ähnelt.
        /// </summary>
        internal static string CrawlerIndexerInterfaceMessage02 {
            get {
                return ResourceManager.GetString("CrawlerIndexerInterfaceMessage02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sende das Element {0} zum Indexieren. ähnelt.
        /// </summary>
        internal static string CrawlerIndexerInterfaceMessage03 {
            get {
                return ResourceManager.GetString("CrawlerIndexerInterfaceMessage03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Indexiere das Element {0}. ähnelt.
        /// </summary>
        internal static string CrawlerIndexerInterfaceMessage04 {
            get {
                return ResourceManager.GetString("CrawlerIndexerInterfaceMessage04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Überprüfen der Übereinstimmung der Werte beim Objekt {0} ähnelt.
        /// </summary>
        internal static string CrawlerIndexerInterfaceMessage05 {
            get {
                return ResourceManager.GetString("CrawlerIndexerInterfaceMessage05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es konnte keine Datenbankverbindung hergestellt werden. Der Name der Tabelle (ID des Jobs) darf nicht leer sein. ähnelt.
        /// </summary>
        internal static string ElementLogContextMessage01 {
            get {
                return ResourceManager.GetString("ElementLogContextMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sende eine HTTP-Anfrage an: {0} ähnelt.
        /// </summary>
        internal static string HttpRequestMessage01 {
            get {
                return ResourceManager.GetString("HttpRequestMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sende eine HTTP-Anfrage an: {0} ähnelt.
        /// </summary>
        internal static string HttpRequestMessage02 {
            get {
                return ResourceManager.GetString("HttpRequestMessage02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Konfiguriere den Proxy: URL={0}, Port={1} ähnelt.
        /// </summary>
        internal static string HttpRequestMessage03 {
            get {
                return ResourceManager.GetString("HttpRequestMessage03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Jobs konnten nicht gelesen werden. Möglicherweise existiert das Verzeichnis {0} nicht oder es fehlen die Berechtigungen. ähnelt.
        /// </summary>
        internal static string JobReaderMessage01 {
            get {
                return ResourceManager.GetString("JobReaderMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Konfiguration des Jobs mit Index {0} ist fehlerhaft und konnte nicht deserialisiert werden. ähnelt.
        /// </summary>
        internal static string JobReaderMessage02 {
            get {
                return ResourceManager.GetString("JobReaderMessage02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Konfiguration des Jobs {0} ist fehlerhaft. Prüfen Sie die URLs. ähnelt.
        /// </summary>
        internal static string JobReaderMessage03 {
            get {
                return ResourceManager.GetString("JobReaderMessage03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei {0} konnte nicht gelesen werden. ähnelt.
        /// </summary>
        internal static string JobReaderMessage04 {
            get {
                return ResourceManager.GetString("JobReaderMessage04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Job {0} wird gestartet. ähnelt.
        /// </summary>
        internal static string JobSchedulerMessage01 {
            get {
                return ResourceManager.GetString("JobSchedulerMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beginn: {0} ähnelt.
        /// </summary>
        internal static string JobSchedulerMessage02 {
            get {
                return ResourceManager.GetString("JobSchedulerMessage02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Job {0} wird beendet. ähnelt.
        /// </summary>
        internal static string JobSchedulerMessage03 {
            get {
                return ResourceManager.GetString("JobSchedulerMessage03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ende: {0} ähnelt.
        /// </summary>
        internal static string JobSchedulerMessage04 {
            get {
                return ResourceManager.GetString("JobSchedulerMessage04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Element konnte nicht an den Index übermittelt werden. ähnelt.
        /// </summary>
        internal static string JsonIndexerMessage01 {
            get {
                return ResourceManager.GetString("JsonIndexerMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die E-Mail konnte nicht verschickt werden. ähnelt.
        /// </summary>
        internal static string MailClientMessage01 {
            get {
                return ResourceManager.GetString("MailClientMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Metadaten-Datei konnte nicht geladen werden. Die Anfrage an lieferte ein ungültiges Ergebnis. ähnelt.
        /// </summary>
        internal static string MetaFileReaderMessage01 {
            get {
                return ResourceManager.GetString("MetaFileReaderMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Programm kann nicht ins standardmäßige Protokollverzeichnis schreiben. ähnelt.
        /// </summary>
        internal static string ProgramMessage01 {
            get {
                return ResourceManager.GetString("ProgramMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starte alle Crawling Tasks ähnelt.
        /// </summary>
        internal static string PublicationCrawlerMessage01 {
            get {
                return ResourceManager.GetString("PublicationCrawlerMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analysiere das Element {0}. ähnelt.
        /// </summary>
        internal static string PublicationCrawlerMessage02 {
            get {
                return ResourceManager.GetString("PublicationCrawlerMessage02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beginne die Arbeit. ähnelt.
        /// </summary>
        internal static string PublicationCrawlerMessage03 {
            get {
                return ResourceManager.GetString("PublicationCrawlerMessage03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nichts zu tun. ähnelt.
        /// </summary>
        internal static string PublicationCrawlerMessage04 {
            get {
                return ResourceManager.GetString("PublicationCrawlerMessage04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prüfe, ob ein Element in der Warteschlange ist ähnelt.
        /// </summary>
        internal static string PublicationCrawlerMessage05 {
            get {
                return ResourceManager.GetString("PublicationCrawlerMessage05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Element {0} konnte nicht vollständig indexiert werden. ähnelt.
        /// </summary>
        internal static string PublicationCrawlerMessage06 {
            get {
                return ResourceManager.GetString("PublicationCrawlerMessage06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Datum {0} konnte nicht geparst werden. Es wird stattdessen das heutige Datum verwendet. ähnelt.
        /// </summary>
        internal static string UtilMessage01 {
            get {
                return ResourceManager.GetString("UtilMessage01", resourceCulture);
            }
        }
    }
}
